# used by server only to configure its port
# RTSS client uses R.server.endpoint and Osier.server.endpoint  
server.endpoint: http://localhost:5577

# shell command to launch R 
R.executable: R --vanilla --quiet

# R can optionally be hosted on a remote machine
R.server.endpoint: http://ub22a.local:5577
#R.server.endpoint: http://localhost:5577
R.server.log: true

# Windows console command to launch OsierCLI
# see Osier-CLI/readme.txt 
Osier.executable: C:\WINAPPS\Osier\ExcelOSR\Addin\OsierCLI

# Osier can optionally be hosted on a remote machine
#Osier.server.endpoint: http://ub22a.local:5577
Osier.server.log: false
